### ISSUE TITLE
As an applicant I can perform the application registration process.

### ISSUE THREAD

**Issue by TechnicallyTiya** [df1217/Capstone_KidSports#10]
- [x] I am able to enter background check information (Step 1).
- [x] I am able to enter coaching preferences (Step 2).
- [x] I am able to enter coaches pledge (Step 3).
- [x] I am able to enter their NFHS Concussion Course certification (Step 4).
- [x] I am able to enter their Positive Coaching Alliance certification (Step 5).
- [x] I am able to enter their Driver's Licence photo (Step 6).
- [x] I am able to enter a photo for their Coach ID Badge (Step 7).
